name: Jib Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  Deploy-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11 for deploy
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github

      - name: Publish to GitHub Container Registry
        run: ./gradlew jib
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}